### ISSUE TITLE
Ao completar quest da senhora, chat fica travado

### ISSUE THREAD

**Issue by nawarian** [tecMTST/imobilidade-urbana#32]
Depois de entregar a bolsa da senhora, se você falar com ela novamente o chat fica travado mesmo se você andar para outros vagões. A única forma de destravar o chat é falando com outras pessoas. Se você tentar puxar o chat com ela de novo, o chat não entra.

[Screencast from 12.12.2023 14:39:28.webm](https://github.com/tecMTST/imobilidade-urbana/assets/3905582/61d55818-cda2-477c-9a8a-881db4ce29bd)

**Comment by DanielSanLopes** [comment]
Solved
