### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by rodigu** [tecMTST/imobilidade-urbana#36]
Forçar fulscreen (não deixar jogar sem estar Fullscreen)

**Comment by nawarian** [comment]
Não tem como "forçar fullscreen" no navegador, isso é uma das regras de ouro dos navegadores. Toda ação pra tocar vídeo, áudio ou mudar pra tela cheia precisa de uma interação do usuário.

O que dá pra fazer é botar um botão que quando apertado abre fullscreen. Pode ser por exemplo uma mensagem "Toque para iniciar" ou mesmo um botão com o ícone de expandir tela (que já tem lá).

**Comment by rodigu** [comment]
> Não tem como "forçar fullscreen" no navegador, isso é uma das regras de ouro dos navegadores. Toda ação pra tocar vídeo, áudio ou mudar pra tela cheia precisa de uma interação do usuário.
> 
> O que dá pra fazer é botar um botão que quando apertado abre fullscreen. Pode ser por exemplo uma mensagem "Toque para iniciar" ou mesmo um botão com o ícone de expandir tela (que já tem lá).

Desculpa, essa issue ficou curta pq a clarificação tá no https://github.com/tecMTST/imobilidade-urbana/issues/35

Quando digo forçar full screen quero dizer não deixar jogar sem estar Fullscreen. Algo como é feito na itch, um "touch to play in Fullscreen."

**Comment by rodigu** [comment]
Se bem que isso não é implementação, é só colocar nas opções da página na itch

**Comment by DanielSanLopes** [comment]
Então, se for publicar pelo itch, então blz

**Comment by nawarian** [comment]
Duplicata da issue #35, e também gerenciada pelo GDD. Fechando esta issue pra organizar melhor nossa vida <3
