### ISSUE TITLE
Check data usage

### ISSUE THREAD

**Issue by rodigu** [tecMTST/imobilidade-urbana#37]
How much data does it take to fully road the game?
Also test data usage while playing the game (just in case unity might be doing some analytics)

**Comment by nawarian** [comment]
O download do jogo hoje é de ~26mb, e leva cerca de 10 segundos para carregar completamente no wi-fi e 2,5 minutos para carregar num 3G bom e 49 segundos num 4G.

![image](https://github.com/tecMTST/imobilidade-urbana/assets/3905582/77bab92e-02a4-40da-9244-ed1ada4fc5c4)
