### ISSUE TITLE
Tela amarela

### ISSUE THREAD

**Issue by rodigu** [tecMTST/imobilidade-urbana#38]
Navegador: Samsung Internet
Dispositivo: A52

Depois de ser pego pela segunda vez, a tela faz o fade amarelo só depois do teleporte, e fica presa no amarelo:

![Screenshot_20231224_191111_Samsung Internet.jpg](https://github.com/tecMTST/imobilidade-urbana/assets/58960796/7954d940-ca35-46c9-aa7d-d686718c20c4)

**Comment by DanielSanLopes** [comment]
Solved
